import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/component/Header";
import { Footer } from "@/component/Footer";

import { Oswald } from 'next/font/google';

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "EVOLVE",
  description: "Generated by create next app",
   icons: {
    icon: '/favicon.ico', 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={oswald.className}>
      <body>
        
      <Header/>
      {children}
      <Footer/>

      </body>
    </html>
  );
}
